#!/bin/sh

here=${PWD}
tmploc=$(mktemp -dq)

cd ${tmploc}

CreateElementsModule Module_test

if [ $? -ne 0 ]; then
  cd ${here}
  rm -rf ${tmploc}
  exit 1
fi

if [ ! -d $Module_test ]; then
  cd ${here}
  rm -rf ${tmploc}
  exit 1
fi

cd ${here}

if [ -d ${tmploc} ]; then
 rm -rf ${tmploc}
fi 

unset tmploc
unset here

exit 0