# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["feature/GithubDoc"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.12
      - name: Install Boost
        run: sudo apt-get install -y libboost-all-dev liblog4cpp5-dev
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen python3-sphinx graphviz
      - name: Use CMake
        run: cmake --version
      - name: Build Doc with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          target: doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ runner.workspace }}/build/doc
      - name: Where are we?
        run: pwd; ls ${{ runner.workspace }}
      - name: And then?
        run: ls ${{ runner.workspace }}; ls ${{ runner.workspace }}/build      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        
 